Add functions to save image directly from the library
adafruit/Adafruit_CircuitPython_VC0706 pull request #18
Opened 2020-09-14 00:35 UTC by Andon-A

Adds a function called save_image to allow for, unsurprisingly, saving the image using only the library. Then added a function called take_and_save that will take the image, save it, and then turn the camera back to video mode. Both examples are updated to take advantage of this.

take_and_save takes three arguments: Filename (Surprising, I know), overwrite, and image size. While I've left a lot of explanations and things, I've taken a picture with four lines of code:
```import board
import adafruit_vc0706
vc0706 = adafruit_vc0706.VC0706(board.UART())
vc0706.take_and_save("quicktest.jpg", True, adafruit_vc0706.IMAGE_SIZE_640x480)
```

Nothing in the library has been re-named or even modified, only added to, so existing code shouldn't be affected. I've tested with no issues on CircuitPython and Windows via a FTDI connector.

2020-09-14 22:00 UTC, tannewt commented
Please checkout this PR where we're discussing a camera API: https://github.com/adafruit/circuitpython/pull/3369 It'd be good to have the same API for this. (I'd love your feedback too since you are currently using the camera.) Thanks!

2020-09-14 22:17 UTC, Andon-A commented
I will have a look in a bit! A unified camera deal would be great, but a lot this sort of stuff is out of my league.

2020-09-14 23:18 UTC, Andon-A commented
Implementing such an API is, well. At like, floor 20, there's no elevators, and I really prefer to be in the park and occasionally poke my head in the lobby for a snack.

To put in other terms: It requires a lot of knowledge I don't have and, to be honest, don't particularly care to learn. I don't like programming much. It seems like a really cool idea, there's some camera-specific issues maybe unless I missed things, but it will not be I that implements it here right now.

2020-09-15 18:30 UTC, tannewt commented
I don't expect you to change the whole api. Instead I'd like `take_and_save` be replaced by a compatible `take_picture` that matches what CircuitPython's `camera` will have. Are you willing to do that?

2020-09-15 18:36 UTC, Andon-A commented
The *only* reason I didn't use `take_picture` in the first place is it's already used and I didn't want to break existing code, so I can do that easily by renaming things. With the discussion of the API and understanding it more, I can easily match that with no issue.

2020-09-15 19:06 UTC, Andon-A commented
Well. I think no issues.

2020-09-16 19:13 UTC, tannewt commented
> The _only_ reason I didn't use `take_picture` in the first place is it's already used and I didn't want to break existing code, so I can do that easily by renaming things. With the discussion of the API and understanding it more, I can easily match that with no issue.

Ah, bummer! I think we should just hold off on unifying the API. We can merge this as-is and follow up with a big restructure when we want them to be the same.

2020-09-16 19:26 UTC, Andon-A commented
I could potentially restructure take_and_save to follow the same form, but still he called take_and_save (or something better), to make unification easier when it does happen?

2020-09-17 18:14 UTC, tannewt commented
@Andon-A Ya, making it take the same arguments as the future take_picture could help. We could even add a comment to `take_picture` recommending using the newer function. Then, when we do change it we say rename `take_and_save` to `take_picture`.

2020-09-17 18:27 UTC, Andon-A commented
Further thinking on this:

While we could use various methods to make `take_picture` function in multiple ways (arguments, constructor variable, etc), but what about leaving the entire class as it is now, but making a new class for the compatibility, say `VC0706_Camera` or something? Old code would default to the old class (which could eventually be removed when it comes time to clean things up), but the new class would be made from the ground up to be in line with the API?

Also, the major thing I am not sure of is the buffer. What exactly is it supposed to be - A variable that's been set aside for use? I THINK the M4 boards have enough ram for this camera but larger images definitely not, and it would infringe on other things so I'm not sure.

2020-09-17 18:28 UTC, Andon-A commented
Oh, also. Would you be available this weekend sometime when I actually go and poke at this? I can hit you up on Discord or wherever for specific things

2020-09-18 18:17 UTC, tannewt commented
> While we could use various methods to make `take_picture` function in multiple ways (arguments, constructor variable, etc), but what about leaving the entire class as it is now, but making a new class for the compatibility, say `VC0706_Camera` or something? Old code would default to the old class (which could eventually be removed when it comes time to clean things up), but the new class would be made from the ground up to be in line with the API?

That's one way to go. I tend to replace things more than I should. The only thing to consider is the code size of having two different implementations to store in memory. We could split them into two files though.

> Also, the major thing I am not sure of is the buffer. What exactly is it supposed to be - A variable that's been set aside for use? I THINK the M4 boards have enough ram for this camera but larger images definitely not, and it would infringe on other things so I'm not sure.

I was thinking it could either be an in-memory buffer, like a bytearray, or a stream, like a file. The latter wouldn't need everything in memory at once.

> Oh, also. Would you be available this weekend sometime when I actually go and poke at this? I can hit you up on Discord or wherever for specific things

I'm around. Let's coordinate a time. I try not to be on the computer a ton but can be if we coordinate.

2020-09-19 18:16 UTC, Andon-A commented
I'm looking at this now, and if it's going to be like you mentioned [here](https://github.com/adafruit/circuitpython/pull/3369#issuecomment-692888048), the only thing I'm not sure of how to handle is the format. The VC0706 only returns a jpg, so I want to make it yell if you try something else. But I'm not sure what to check against for that, especially without having the camera module opened as well.

Feel free to poke me here or on Discord whenever's handy for you, I'm basically going to be here all weekend

2020-09-20 02:49 UTC, Andon-A commented
So the updates have done largely what I've said I was going to do. Still not sure how to handle that format, but otherwise it works. Had to fiddle with a few other things to get stuff to work *well*, but it's all in the commit notes.

Examples need to be updated still. And the learn guide will need an update, too.

2020-09-21 23:36 UTC, tannewt requested changes
Sorry I didn't see this over the weekend. Please mention me on Discord to coordinate. I don't read email until Monday.

2020-09-21 23:36 UTC, tannewt commented on examples/vc0706_snapshot_filesystem.py
> +imgfile.close()
Use a with block here and in the other example. It's better because the file will be closed even if an exception happens.

```suggestion
with open(IMAGE_FILE, "wb") as imgfile:
    vc0706.take_picture(imgfile, 640, 480)  # You can also use 320 x 240 or 160 x 120
```

2020-09-21 23:36 UTC, tannewt commented on examples/adafruit_vc0706.py
> +# The MIT License (MIT)
Delete this file. It's in examples.

2020-09-21 23:36 UTC, tannewt commented on adafruit_vc0706.py
> +    return size
I think you could simplify this by using a dictionary. Something like:

```python
sizes = {
(640, 480): IMAGE_SIZE_640x480
# etc
}

def get_image_size(width, height):
    t = (width, height)
    if t not in sizes:
        raise ValueError()
    return sizes[t]
```

2020-09-21 23:36 UTC, tannewt commented on adafruit_vc0706.py
> +        return bufflen
I'm worried that this is adding a lot of code. What board are you testing with? What do you think about only adding the new Camera class?

2020-09-21 23:36 UTC, tannewt commented on adafruit_vc0706.py
> +class VC0706Camera:
The name of the device is in the library already. I think I'd simplify this library to reduce duplicating code between it and the old version.

```suggestion
class Camera:
```

2020-09-22 00:30 UTC, Andon-A commented on adafruit_vc0706.py
> +        return bufflen
That'd make sense! read_picture_into is already in the existing code but I can strip out everything else I've added to it.

2020-09-22 00:37 UTC, Andon-A commented on examples/adafruit_vc0706.py
> +# The MIT License (MIT)
Sneaky little bugger. It's been deleted.

2020-09-22 00:39 UTC, Andon-A commented on examples/vc0706_snapshot_filesystem.py
> +imgfile.close()
Looks nicer, too. Done.

2020-09-22 00:42 UTC, Andon-A commented on adafruit_vc0706.py
> +    return size
A much easier and simpler way of doing it.

2020-09-22 17:34 UTC, tannewt commented on adafruit_vc0706.py
> +        return bufflen
Did you do this as well? I don't see any changes here. I hope you didn't accidentally do it with the examples version.

2020-10-05 01:53 UTC, Andon-A commented on adafruit_vc0706.py
> +        return bufflen
OK, so, it's been a busy few weeks.

Apparently, I did it and.... uh, didn't save it, so it never got committed, etc etc.

Committed now.

2020-10-05 21:04 UTC, tannewt requested changes
I've suggested removing some APIs and marking some private. The new class should be smaller and simpler ideally.

Let me know if you'd like me to reorganize it. I'll need your help testing though because I don't have a camera.

2020-10-05 21:04 UTC, tannewt commented on adafruit_vc0706.py
> +        self.set_img_size(size)
```suggestion
        self.img_size = size
```

2020-10-05 21:04 UTC, tannewt commented on adafruit_vc0706.py
> +    def stop_video(self):
```suggestion
    def _stop_video(self):
```

2020-10-05 21:04 UTC, tannewt commented on adafruit_vc0706.py
> +    def resume_video(self):
```suggestion
    def _resume_video(self):
```

2020-10-05 21:04 UTC, tannewt commented on adafruit_vc0706.py
> +    def read_picture_into(self, buf):
```suggestion
    def _read_picture_into(self, buf):
```

2021-01-06 16:52 UTC, kattni commented
@Andon-A Hey! Thanks for the contribution. Scott suggested a few changes. Are you still interested in working on this?

2021-01-07 20:25 UTC, Andon-A commented
@kattni Oh gosh, I completely forgot about this. I'll try to find some time to look at it in the upcoming few weeks and remember where I was.

2021-04-19 17:20 UTC, Andon-A commented
I saw that there's camera support being worked on for CircuitPython. I have no idea when I'll end up working on this again, and as the camera updates may change how things are wanted, I'm just going to close this and come back to it at a later date.

2021-04-19 17:20 UTC, closed without merging

2021-04-19 20:56 UTC, tannewt commented
@jepler Food for thought.