Fix documentation
adafruit/Adafruit_CircuitPython_VC0706 pull request #22
Opened 2022-03-28 15:39 UTC by Neradoc

Missing new lines for parameters list.

2022-03-29 14:19 UTC, tekktrik requested changes

2022-03-29 14:19 UTC, tekktrik commented on adafruit_vc0706.py
>          args = 0 to unset, 1 to set
Want to turn this into a `:param:` line?

2022-03-29 15:31 UTC, tekktrik commented on adafruit_vc0706.py
>          args = 0 to unset, 1 to set
The type would be `bool` according to the docstring

2022-04-04 16:21 UTC, FoamyGuy approved these changes
Looks good to me, tested with local sphinx build. Parameters in docs page from this branch looks better than current docs page.

@tekktrik we can update the args docstring in a seperate PR. I'll make a new one today for that.

2022-04-04 16:22 UTC, merged